### ISSUE TITLE
Java form-data upload failes with HTTP error 503

### ISSUE THREAD

**Issue by PlasticGhoul** [SasaKaranovic/VU1-Server#45]
Hi,

I'm currently writing a mod for Minecraft which obviously means I have to write the API calls in Java.

At this moment I'm failing to upload an image to the API server wich is reponding with an HTTP error 503 and the Log says the following to my upload attempt:

> 2024-05-06 19:29:42,042 ERROR handle_image_upload(193) imgfile field missing from request.
> 2024-05-06 19:29:42,043 ERROR post(166) Handle image upload failed

My Java code is the following (sorry if it is messed up - I'm not a software developer and this is a very early WIP):
```
String apiUrl = MCVUDialsConfig.vuServerApiBaseUrl + "/api/v0/dial/" + dialUid + "/image/set?key="
        + MCVUDialsConfig.vuServerApiKey + "&imgfile=" + dialImage;

// Create a boundary for the multipart/form-data request
String boundary = "===" + System.currentTimeMillis() + "===";

URL url = new URL(apiUrl);
HttpURLConnection connection = (HttpURLConnection) url.openConnection();

// Set the necessary headers
connection.setRequestMethod("POST");
connection.setRequestProperty("Content-Type", "multipart/form-data; boundary=" + boundary);
connection.setDoOutput(true);

// Read the file from the classpath
InputStream fileStream = MCVUDials.class.getResourceAsStream("/" + dialImage);

// Write the request body
try (OutputStream outputStream = connection.getOutputStream();
        PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputStream, "UTF-8"), true)) {
    // Write boundary
    writer.append("--").append(boundary).append("\r\n");
    // Write Content-Disposition header
    writer.append("Content-Disposition: form-data; name=\"file\"; filename=\"").append(dialImage)
            .append("\"\r\n");
    // Write Content-Type header
    writer.append("Content-Type: ").append("application/octet-stream").append("\r\n");
    writer.append("\r\n").flush();

    // Write file content
    byte[] buffer = new byte[4096];
    int bytesRead;
    while ((bytesRead = fileStream.read(buffer)) != -1) {
        outputStream.write(buffer, 0, bytesRead);
    }
    outputStream.flush();

    // Write boundary
    writer.append("\r\n").flush();
    writer.append("--").append(boundary).append("--\r\n").flush();
}

// Read the response
StringBuilder response = new StringBuilder();
try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
    String inputLine;
    while ((inputLine = in.readLine()) != null) {
        response.append(inputLine);
    }
}

// Print the response
System.out.println("Response: " + response.toString());

// Close the connection
connection.disconnect();
```

In the first line you can clearly see that the `imgfile` field is present.

What possibilities do I have to debug further into this on VUServer side?
Do you maybe already see what I'm missing?

Also sorry if this is the wrong chanel for this type of questions.
Thank you :)

**Comment by SasaKaranovic** [comment]
Hi @PlasticGhoul 

It looks like you are not sending a proper POST request to set the image.

You should pass the `imgfile` parameter in the form-data (body) part of the POST method.
I am not sure how a proper request would look in Java but I think you are missing "Content-Length"
Your Content-Type should be `multipart/form-data`. It looks like you are setting it twice and also to two different types, once to `multipart/form-data` and then in request body to `application/octet-stream`.

It would probably be difficult to debug this from the VU Server side since your application is sending a malformed request.
Maybe try writing your request to a string and then print it out to console to verify it is formatted as you expect it to be.

**Comment by PlasticGhoul** [comment]
Thanks for the really quick response.
I indeed oversaw a few things and I thought since Java told me everything is good and I couldn't make anything out of the "imgfile field missing" error.

I will try a few things tomorrow when I have time. Didn't thought you'll respond THAT quick :D

**Comment by PlasticGhoul** [comment]
I couldn't wait and got it running with the following code:

```
String apiUrl = MCVUDialsConfig.vuServerApiBaseUrl + "/api/v0/dial/" + dialUid + "/image/set?key="
        + MCVUDialsConfig.vuServerApiKey + "&imgfile=" + dialImage;

// Create a boundary for the multipart/form-data request
String boundary = "===" + System.currentTimeMillis() + "===";

URL url = new URL(apiUrl);
HttpURLConnection connection = (HttpURLConnection) url.openConnection();

// Set the necessary headers
connection.setRequestMethod("POST");
connection.setRequestProperty("Content-Type", "multipart/form-data; boundary=" + boundary);
connection.setDoOutput(true);

// Read the file from the classpath
InputStream fileStream = MCVUDials.class.getResourceAsStream("/" + dialImage);

// Write the request body
try (OutputStream outputStream = connection.getOutputStream();
        PrintWriter writer = new PrintWriter(new OutputStreamWriter(outputStream, "UTF-8"), true)) {
    // Write boundary
    writer.append("--").append(boundary).append("\r\n");
    // Write Content-Disposition header
    writer.append("Content-Disposition: form-data; name=\"imgfile\"; filename=\"").append(dialImage)
            .append("\"\r\n");
    // Write Content-Type header
    writer.append("Content-Type: ").append("multipart/form-data").append("\r\n");
    writer.append("\r\n").flush();

    // Write file content
    byte[] buffer = new byte[4096];
    int bytesRead;
    while ((bytesRead = fileStream.read(buffer)) != -1) {
        outputStream.write(buffer, 0, bytesRead);
    }
    outputStream.flush();

    // Write boundary
    writer.append("\r\n").flush();
    writer.append("--").append(boundary).append("--\r\n").flush();
}

// Read the response
StringBuilder response = new StringBuilder();
try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
    String inputLine;
    while ((inputLine = in.readLine()) != null) {
        response.append(inputLine);
    }
}

// Close the connection
connection.disconnect();
```

Thanks again, your tips really helped.

**Comment by SasaKaranovic** [comment]
That's great news! I'm glad you got it working!

I'm not sure how you are using it, but if you want to showcase your setup or share the script/setup with others, please feel free to do that on the [VU Forum](https://forum.vudials.com). I'm sure there are other people who would love to use it or draw inspiration from it. :)

**Comment by PlasticGhoul** [comment]
Will do that once it's finished. It's going to be a mod for Minecraft that I will be sharing with everyone :)
