### ISSUE TITLE
Info on set background image

### ISSUE THREAD

**Issue by docop** [SasaKaranovic/VU1-Server#47]
Hi
 I try to set an image, but it is not possible via the webgui as 1: the image default is only a white square. Not the one with the vu-dial txt on it, just like on the display. And 2 - we cannot click and cannot browse to folder and select a file to upload.
 But part of example with the: post and get.. and on how to push. And as those 2 how to fit in a command .. do you have an example on how to check status.. like at your : https://docs.vudials.com/api/dial_UID_easing_get/

 Or better.. how to upload from terminal an image.. via curl ?
Thanks in advance

**Comment by SasaKaranovic** [comment]
I'm not sure I entirely understood your question but for the terminal example, you could try something like 

```
curl --location 'http://localhost:5340/api/v0/dial/YOUR_DIAL_UID/image/set' \
--form 'imgfile=@"/C:/image.png"' \
--form 'key="cTpAWYuRpA2zx75Yh961Cg"'
```

Make sure your image is exactly `144x200`.
