### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by bonds** [SasaKaranovic/VU1-Server#48]
Please add a license file so everyone is clear on the license for this repo! I'm trying to package it for a linux OS to make it easier for others to use, but I expect the maintainers will require clarity on the license.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Maybe MIT? AGPL?

**Comment by SasaKaranovic** [comment]
Thanks for the suggestion! I will think about what is the appropriate license and then add it to the repo.

p.s. Sorry about late reply. I was away on vacation for a while. :)
