### ISSUE TITLE
`serial_driver` timeouts

### ISSUE THREAD

**Issue by hanshuebner** [SasaKaranovic/VU1-Server#50]
I'm running VU-Server (62a405972c629858085cf17ec5e3d2b110a34581 as of May 5) on macOS using python 3.12.4.  Things work fine, but every couple of seconds, updates to the dials freeze for a while:
```
Aug 16 2024 07:39:23.743 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786763.743368 > 1723786762.728828)
Aug 16 2024 07:39:49.548 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786789.5483541 > 1723786788.52704)
Aug 16 2024 07:39:56.757 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786796.7575738 > 1723786795.728696)
Aug 16 2024 07:40:20.154 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786820.154259 > 1723786819.1267421)
Aug 16 2024 07:40:27.345 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786827.345099 > 1723786826.329184)
Aug 16 2024 07:40:49.155 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786849.155023 > 1723786848.12682)
Aug 16 2024 07:40:55.949 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786855.9497752 > 1723786854.928881)
Aug 16 2024 07:41:19.742 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786879.742584 > 1723786878.727286)
Aug 16 2024 07:41:51.155 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786911.155242 > 1723786910.1270971)
Aug 16 2024 07:41:57.938 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786917.9386728 > 1723786916.9288309)
Aug 16 2024 07:42:20.942 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786940.9424572 > 1723786939.92702)
Aug 16 2024 07:43:15.541 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723786995.5416708 > 1723786994.533045)
Aug 16 2024 07:43:26.542 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723787006.5427809 > 1723787005.527624)
Aug 16 2024 07:43:56.336 pid:88103 serial_driver.py         158 ERROR Timeout occured (1723787036.336643 > 1723787035.327183)
```
The problem is independent of whether the dials are connected to a hub or directly to the USB port of the Machine.

I'm seeing the same behavior on a PC running Linux.

The problem occurs with out without VU1 dials connected to the hub, albeit less frequently when there are no secondary devices connected.

Any ideas as to what could be the cause of this?

Thanks,
Hans

**Comment by hanshuebner** [comment]
Problem remains. I'm working around the issue with a small timeout, but it is annoying because I can't really use the meters for real-time displays this way.

**Comment by SasaKaranovic** [comment]
Hey @hanshuebner !

Can you check if you have the same issue with different USB cable and/or using a different USB port?
Does power-cycling the VU hub AND restarting the VU server change anything?

This issue usually indicates that VU server has not received a response from the VU dials hub within the set time window so it's timing out.

p.s. Sorry about late reply. I was away on vacation for a while. :)

**Comment by hanshuebner** [comment]
Hi Sasa, welcome back after your vacation and thank you for responding! :)

> Can you check if you have the same issue with different USB cable and/or using a different USB port?

The problem occurs on different machines.  I've been able to reproduce it both with the supplied USB-A/C as well as a USB-C/C cable on different ports.

> Does power-cycling the VU hub AND restarting the VU server change anything?

No.

**Comment by SasaKaranovic** [comment]
That's very odd behaviour. :\

Does this happen all the time (ie immediately at the start) or after some time?
You mentioned that increasing the timeout resolves the issue but obviously adds the unwanted delay. To what value are you changing the timeout?

How many VU dials do you have and how are they connected?
You said that this issue does not happen (or happens less often) when you have just the VU hub connected?

There is a log file generated by the VU server, when this issue happens, could you take the log file and attach it so we can take a peek and see if anything funny is going around?

**Comment by hanshuebner** [comment]
The behavior is always present, no matter how long the server is running.  I can mitigate the freezing effect by reducing the timeout to `read_until_response`, but that does not really provide a pleasantly smooth experience.

Here is some server log output with five dials:
```
[...]
Sep 05 2024 06:29:18.641 pid:3688 server.py                546 INFO  VU1 HUB port: /dev/cu.usbserial-DQ014WTA - FT230X Basic UART
Sep 05 2024 06:29:18.648 pid:3688 server_dial_handler.py    26 INFO  Communication timeout set to 10 seconds
[...]
Sep 05 2024 06:29:51.765 pid:3688 serial_driver.py         158 ERROR Timeout occured (1725510591.765365 > 1725510590.755931)
Sep 05 2024 06:30:02.366 pid:3688 serial_driver.py         158 ERROR Timeout occured (1725510602.366484 > 1725510601.355411)
Sep 05 2024 06:30:12.969 pid:3688 serial_driver.py         158 ERROR Timeout occured (1725510612.969589 > 1725510611.955519)
Sep 05 2024 06:30:35.370 pid:3688 serial_driver.py         158 ERROR Timeout occured (1725510635.370015 > 1725510634.3547661)
Sep 05 2024 06:30:44.360 pid:3688 serial_driver.py         158 ERROR Timeout occured (1725510644.36007 > 1725510643.355975)
```
Here is some output with just the Hub and no additional dials:
```
Sep 05 2024 06:36:10.351 pid:4340 server_dial_handler.py    26 INFO  Communication timeout set to 10 seconds
Sep 05 2024 06:36:10.518 pid:4340 server.py                552 INFO  No additional dials found. Searching the bus for new ones...
[...]
Sep 05 2024 06:36:33.340 pid:4340 serial_driver.py         158 ERROR Timeout occured (1725510993.340141 > 1725510992.3265789)
Sep 05 2024 06:36:44.335 pid:4340 serial_driver.py         158 ERROR Timeout occured (1725511004.335841 > 1725511003.326557)
Sep 05 2024 06:36:54.934 pid:4340 serial_driver.py         158 ERROR Timeout occured (1725511014.9341462 > 1725511013.926773)
Sep 05 2024 06:37:05.136 pid:4340 serial_driver.py         158 ERROR Timeout occured (1725511025.13628 > 1725511024.127081)
```
From this, I would conclude that the problem is not really affected by the number of dials connected to the Hub.
